### ISSUE TITLE
Svelte-Meetup anlegen (see description)

### ISSUE THREAD

**Issue by nika-d** [nika-d/svelte-berlin-meetup#4]
Das Svelte-Meetup soll einerseits mit dem Charité-Meetup (oder Gruppe?) sichtbar verknüpft sein, aber andererseits soll es auch eine ganz eigene Einheit sein und mit anderen Organisationen verknüpfbar sein. Dabei sollen natürlich die Teilnehmer/Kontakte des Svelte-Meetups erhalten bleiben.

**Comment by nika-d** [comment]
Text für Gruppe: 

[english below]

Hallo aus dem Geschäftsbereich IT der Charité-Universitätsmedizin Berlin! 
Wir sind IT-Menschen in den verschiedensten Bereichen, Frontend-Devs, Data Analysts, SAP-Admins, Hardware-Consultants, all levels Support, alle dazwischen und außerhalb. 
Mit dieser Meetup-Gruppe möchten wir alle Interessierten herzlich einladen, sich mit uns auszutauschen. 

Hello from the IT department of the Charité-Universitätsmedizin Berlin! 
We are IT people in a wide variety of areas, frontend devs, data analysts, SAP admins, hardware consultants, all levels of support, everyone in between and outside. 
With this meetup group we would like to warmly invite everyone who is interested to exchange ideas with us. 

Text für ersten Termin: 

[english below]

Alle mögen Svelte, auch wenn es immer noch nicht in den Jobbeschreibungen angekommen ist (auch bei uns in CharITé nicht). Lasst uns mehr drüber reden, Erfahrungen austauschen und uns zusammentun! 
Im ersten Treffen begrüßen wir ... , und lauschen einem Vortrag zum Thema ... .

Everyone likes Svelte, even if it still hasn't made it into the job descriptions (not even here at CharITé). Let's talk more about it, exchange experiences and build a community of practice! 
In the first meeting we welcome... to listen to a lecture on the topic....

**Comment by alfirak** [comment]
Gruppe:
https://www.meetup.com/charite-berlin-it-meetup-group/

**Comment by alfirak** [comment]
Gruppe war umgezogen: 
https://lu.ma/charite-berlin-it
Auf meetup.com mit günstigste Tarif kann man fast nichts machen, und auf lu.ma gibt es mehr Möglichkeiten kostenlos.

**Comment by alfirak** [comment]
Unser erste Meetup:
https://lu.ma/ud76698y
